"use client";

import Link from "next/link";
import { useEffect } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Button } from "@/components/buttons/Button";
import { Card } from "@/components/elements/Card";
import { EmptyState } from "@/components/elements/EmptyState";
import { ErrorState } from "@/components/elements/ErrorState";
import { Loader } from "@/components/elements/Loader";
import { ZyraMark } from "@/features/zyra/elements/ZyraMark";
import { cx } from "@/lib/classNames";
import { useZyra } from "@/hooks";
import type { ZyraSuggestionResponse } from "@/types/zyra";

const formatDateTime = (iso: string) =>
  new Date(iso).toLocaleString("en-US", {
    day: "2-digit",
    month: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });

const getSuggestionTitle = (suggestion: ZyraSuggestionResponse) => {
  switch (suggestion.suggestionType) {
    case "MATCH_OF_THE_DAY":
      return "Match of the day";
    case "PLACE_RECOMMENDATION":
      return "Places for you";
    case "USER_RECOMMENDATION":
      return "Compatible people";
    default:
      return "Suggestion";
  }
};

const getSuggestionMessage = (suggestion: ZyraSuggestionResponse) => {
  if (suggestion.payload && typeof suggestion.payload.message === "string") {
    return suggestion.payload.message;
  }
  return "Suggestion generated by Zyra.";
};

const getAction = (suggestion: ZyraSuggestionResponse) => {
  switch (suggestion.suggestionType) {
    case "MATCH_OF_THE_DAY":
      return { label: "Go to matches", href: "/matches" };
    case "PLACE_RECOMMENDATION":
      return { label: "Open map", href: "/map" };
    case "USER_RECOMMENDATION":
      return { label: "Discover people", href: "/matches" };
    default:
      return null;
  }
};

export const ZyraSuggestionsFlow = () => {
  const { suggestions, loadingSuggestions, error, actions } = useZyra();

  useEffect(() => {
    actions.fetchSuggestions({ size: 20 }).catch(() => undefined);
  }, [actions]);

  const hasData = suggestions.length > 0;

  return (
    <Card className="space-y-4 p-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <ZyraMark size="sm" />
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-subtle">
              Zyra suggestions
            </p>
            <h2 className="text-xl font-semibold text-foreground">
              Latest recommendations
            </h2>
          </div>
        </div>
        <span className="rounded-full border border-border/70 bg-surface-muted px-2 py-1 text-[10px] font-semibold uppercase tracking-wide text-foreground">
          AI
        </span>
      </div>

      {loadingSuggestions && !hasData ? (
        <div className="flex items-center gap-3 text-sm text-muted">
          <Loader size="sm" />
          <span>Loading suggestions...</span>
        </div>
      ) : null}

      {error && !hasData ? (
        <ErrorState
          title="Unable to load suggestions"
          description={error.message}
        />
      ) : null}

      {!loadingSuggestions && !error && !hasData ? (
        <EmptyState
          title="No suggestions"
          description="Generate a suggestion from Zyra to see results here."
        />
      ) : null}

      {hasData ? (
        <div className="space-y-3">
          {suggestions.map((suggestion) => {
            const action = getAction(suggestion);
            const message = getSuggestionMessage(suggestion);
            const context =
              suggestion.payload && typeof suggestion.payload.context === "string"
                ? suggestion.payload.context
                : null;

            return (
              <div
                key={suggestion.id}
                className={cx(
                  "rounded-[var(--radius-md)] border border-border/70 bg-surface p-3"
                )}
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0 space-y-1">
                    <p className="text-sm font-semibold text-foreground">
                      {getSuggestionTitle(suggestion)}
                    </p>
                    <div className="space-y-2 text-sm text-muted">
                      <ReactMarkdown
                        remarkPlugins={[remarkGfm]}
                        components={{
                          p: (props) => <p className="text-inherit" {...props} />,
                          ul: (props) => (
                            <ul className="list-disc space-y-1 pl-4 text-inherit" {...props} />
                          ),
                          ol: (props) => (
                            <ol className="list-decimal space-y-1 pl-4 text-inherit" {...props} />
                          ),
                          li: (props) => <li className="text-inherit" {...props} />,
                          a: (props) => (
                            <a
                              {...props}
                              target="_blank"
                              rel="noreferrer"
                              className="underline decoration-current/40 transition hover:decoration-current"
                            />
                          ),
                          strong: (props) => <strong className="font-semibold" {...props} />,
                          em: (props) => <em className="italic" {...props} />,
                          code: (props) => (
                            <code className="rounded bg-surface-muted px-1.5 py-0.5 font-mono text-[12px]" {...props} />
                          ),
                        }}
                      >
                        {message}
                      </ReactMarkdown>
                    </div>
                    {context ? (
                      <p className="text-xs text-subtle">Context: {context}</p>
                    ) : null}
                  </div>
                  <span className="shrink-0 rounded-full border border-zyra-border/50 bg-zyra-glow/30 px-2 py-0.5 text-[10px] font-medium text-zyra-text">
                    {getSuggestionTitle(suggestion)}
                  </span>
                </div>
                <div className="mt-2 flex items-center justify-between text-[11px] text-subtle">
                  <span>{formatDateTime(suggestion.createdAt)}</span>
                  {action ? (
                    <Link href={action.href} className="text-foreground hover:underline">
                      {action.label}
                    </Link>
                  ) : null}
                </div>
              </div>
            );
          })}
        </div>
      ) : null}
    </Card>
  );
};
