package com.syncro.backend.domain.analytics.entity;

public enum AnalyticsEventType {
    USER_REGISTERED,
    ONBOARDING_COMPLETED,
    APP_OPEN,
    MATCH_SECTION_OPENED,
    MAP_OPENED,
    PROFILE_VIEWED,
    SESSION_DURATION,
    FEEDBACK_SUBMITTED,
    BUDGET_SIMULATION_RUN,
    BUDGET_TRACKING_ENTRY_CREATED,
    STARTER_KIT_GENERATED,
    MICRO_TEST_ASSIGNED,
    MICRO_TEST_COMPLETED
}
